name 'MiniProject'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures MiniProject'
long_description 'Installs/Configures MiniProject'
version '0.1.0'
